openapi: 3.0.1
info:
  title: Fit Strike API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get Users
      responses:
        '200':
          description: A list of users
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:911167911476:function:fit-strike-api/invocations
        passthroughBehavior: when_no_match
        timeoutMillis: 29000
components:
  securitySchemes:
    cognitoAuth:
      type: apiKey
      name: Authorization
      in: header