name: Deploy API Gateway

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0
            
            - name: Terraform init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve